config/routes.rb
Rails.application.routes.draw do
  
  mount Blacklight::Engine => '/'
  
    concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
  end

  devise_for :users
  mount CurationConcerns::Engine, at: '/'
  resources :welcome, only: 'index'
  root 'welcome#index'
  curation_concerns_collections
  curation_concerns_basic_routes
  curation_concerns_embargo_management
  concern :exportable, Blacklight::Routes::Exportable.new

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

  get 'authorities/:authority/:id', to: 'authorities#show', as: 'authority', :constraints => { authority: /(agent|concept|place|resourcetype|language)/ }
  resources :records

end

app/controllers/records_controller.rb
# Extends and customizes the RecordsController in hydra-editor
class RecordsController < ApplicationController
  include RecordsControllerBehavior
  include AuthoritiesHelper

  def index
    redirect_to "/"
  end

  def show
    resource = ActiveFedora::Base.find(params[:id])
    if (resource.nil?)
      flash[:error] = "Resource doesn't exist: #{params[:id]}"
      redirect_to "/"
    else
      redirect_to "/authorities/#{resource.class.name.downcase}/#{params[:id]}"
    end
  end

  def deny_access(exception)
    redirect_to({ controller: :catalog, action: 'show' }, alert: "Error: #{exception.message}")
  end

  def build_form
    resource.attributes.each do |key, value|
      hash_to_uri value
    end
    form_class.new(resource)
  end

  def set_attributes
    resource.attributes = collect_form_attributes
    resource.attributes.each do |key, value|
      if value.is_a? ActiveTriples::Relation
        values = []
        value.map { |v| values << to_hash(v) }
        value.clear.push values
      else
         resource.attributes[key] = to_hash(value)
      end
    end
  end

  protected

    def redirect_after_create
      redirect_after_update
    end

    def redirect_after_update
      "/authorities/#{resource.class.name.downcase}/#{resource.id}"
    end
end

app/views/records/_record_form.html.erb
<style>input#place_point {width: 555px;}</style>
<%= simple_form_for form, url: record_form_action_url(form), html: { class: 'editor' } do |f| %>

  <%= hidden_field_tag :type, params[:type] %>
  <div id="descriptions_display">
    <h2>Information</h2>

    <div class="well">
      <% (f.object.terms).each do |term| %>
        <%= render_edit_field_partial(term, f: f) %>
      <% end %>
    </div>
  </div>

  <div class="form-actions">
    <div class="primary-actions">
      <%= f.submit 'Save', class: 'btn btn-primary' %>
      <%= link_to t(:'helpers.action.cancel'), main_app.root_path, class: 'btn btn-link' %>
    </div>
  </div>
<% end %>

app/views/records/_render_form.html.erb
<% if Authority.is_authority?(@record) %>
  <%= render partial: 'records/record_form' %>
<% else %>
  <h2>Please choose an Authority type: </h2>
  <%= link_to "Select Type", "#{records_path}/new", class: 'btn btn-default' %>
<% end %>

app/views/records/edit.html.erb
<h1><%= edit_record_title %></h1>
<%= render partial: 'records/render_form' %>

app/views/records/new.html.erb
<h1><%= new_record_title %></h1>
<%= render partial: 'records/render_form' %>